image:
  file: .gitpod.Dockerfile
tasks:
  - init: pip3 install -r requirements.txt && ./setup_unity.sh
    command: autopep8 . --recursive --in-place && pip3 install --editable . && (pytest || true) && mypy --strict --exclude='src' . && find src tests -name "*.h" -o -name "*.c" | xargs clang-format -i && rm -rf build && mkdir build && cd build && cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .. && (make || true) && cd .. && find src tests -name "*.h" -o -name "*.c" | xargs clang-tidy -p build && python src/benchmarks/call_benchmark.py
vscode:
  extensions:
    - streetsidesoftware.code-spell-checker # The Code Spell Checker extension is GPLv3-licensed, separate from this project. See its docs for details.
    - ms-toolsai.jupyter # The Jupyter extension is MIT-licensed, separate from this project. See its docs for details.
    - ms-toolsai.jupyter-keymap # The Jupyter Keymap extension is MIT-licensed, separate from this project. See its docs for details.
    - ms-toolsai.jupyter-renderers # The Jupyter Notebook Renderers extension is MIT-licensed, separate from this project. See its docs for details.
    - ms-toolsai.vscode-jupyter-cell-tags # The Jupyter Cell Tags extension is MIT-licensed, separate from this project. See its docs for details.
    - ms-toolsai.vscode-jupyter-slideshow # The Jupyter Slide Show extension is MIT-licensed, separate from this project. See its docs for details.
    - ms-python.python # The Python extension is MIT-licensed, separate from this project. Dependencies: Jupyter (MIT), Pylance (Microsoft proprietary). See docs for details.
    - llvm-vs-code-extensions.vscode-clangd # The clangd extension is MIT-licensed, separate from this project. See its docs for details.
    - ms-vscode.makefile-tools # The Makefile Tools extension is MIT-licensed, separate from this project. See its docs for details.
    - ms-vscode.cmake-tools # The CMake Tools extension is MIT-licensed, separate from this project. See its docs for details.
