name: Benchmarks

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      - name: Setup Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Install local package
        run: |
          python -m pip install --editable .
      - name: Calculate and log performance
        run: |
          python src/benchmarks/call_benchmark.py > benchmarks-${{ matrix.os }}-${{ matrix.python-version }}.txt
          cat benchmarks-${{ matrix.os }}-${{ matrix.python-version }}.txt
      - name: Upload benchmarks
        uses: actions/upload-artifact@604373da6381bf24206979c74d06a550515601b9
        with:
          name: benchmarks-${{ matrix.os }}-${{ matrix.python-version }}
          path: benchmarks-${{ matrix.os }}-${{ matrix.python-version }}.txt
        if: ${{ always() }}
