name: Benchmarks

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      - name: Setup Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Install local package
        run: |
          python -m pip install --editable .
      - name: Calculate and log performance
        run: |
          python src/benchmarks/call_benchmark.py > benchmarks-${{ matrix.os }}-${{ matrix.python-version }}.txt
          cat benchmarks-${{ matrix.os }}-${{ matrix.python-version }}.txt
      - name: Upload benchmarks
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
        with:
          name: benchmarks-${{ matrix.os }}-${{ matrix.python-version }}
          path: benchmarks-${{ matrix.os }}-${{ matrix.python-version }}.txt
        if: ${{ always() }}
