name: Python Build

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]

    env:
      MANYLINUX_DOCKER_IMAGE: quay.io/pypa/manylinux_2_28_x86_64

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - name: Setup Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build package (Linux)
        if: runner.os == 'Linux'
        run: |
          docker run --rm --name manylinux -v $(pwd):/bytecorefast $MANYLINUX_DOCKER_IMAGE /bin/bash -c "cd bytecorefast && /opt/python/cp311-cp311/bin/python3.11 -m build && mkdir dist/wheels && mv dist/*.whl dist/wheels && auditwheel repair dist/wheels/*.whl -w dist/ && rm -rf dist/wheels"
      - name: Build package (macOS and Windows)
        if: runner.os == 'macOS' || runner.os == 'Windows'
        run: python -m build
      - name: Test self building package
        run: |
          pip install dist/bytecorefast-*.tar.gz
          python -c "import bytecorefast; print(bytecorefast)"
        shell: bash
      - name: Upload distribution archives
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
        with:
          name: distribution-archives-${{ matrix.os }}-${{ matrix.python-version }}
          path: dist

  download:

    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e
      with:
        path: distribution-archives
        pattern: distribution-archives-*
        merge-multiple: true
    - run: ls --recursive distribution-archives
