name: Python Build

on: [push]


jobs:
  python-tests:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Lint with autopep8 and get statistics from flake8
      run: |
        # exit-zero treats all errors as warnings.
        # show statistics for Python syntax errors or undefined names.
        # the GitHub editor is 127 chars wide.
        flake8 . --count --exit-zero --extend-ignore E402 --max-complexity=10 --max-line-length=127 --show-source --statistics
        # stop the build if there are Python syntax errors.
        autopep8 . --ignore E402 --recursive --diff --exit-code
    - name: Install local package
      run: |
        python -m pip install --editable .
    - name: Test with pytest
      run: |
        coverage run -m pytest
    - name: Report coverage statistics on modules
      run: |
        coverage report --fail-under=80 --show-missing
    - name: Type checking with mypy
      run: |
        mypy --strict --exclude='src' .

  build:

    needs: python-tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]

    env:
      MANYLINUX_DOCKER_IMAGE: quay.io/pypa/manylinux_2_28_x86_64

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - name: Setup Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build package (Linux)
        if: runner.os == 'Linux'
        run: |
          docker run --rm --name manylinux -v $(pwd):/bytecorefast $MANYLINUX_DOCKER_IMAGE /bin/bash -c "cd bytecorefast && /opt/python/cp311-cp311/bin/python3.11 -m build && mkdir dist/wheels && mv dist/*.whl dist/wheels && auditwheel repair dist/wheels/*.whl -w dist/ && rm -rf dist/wheels"
      - name: Build package (macOS and Windows)
        if: runner.os == 'macOS' || runner.os == 'Windows'
        run: python -m build
      - name: Test self building package
        run: |
          pip install dist/bytecorefast-*.tar.gz
          python -c "import bytecorefast; print(bytecorefast)"
        shell: bash
      - name: Upload distribution archives
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
        with:
          name: distribution-archives-${{ matrix.os }}-${{ matrix.python-version }}
          path: dist

  combine:

    needs: [python-tests, build]
    runs-on: ubuntu-latest

    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e
      with:
        path: distribution-archives
        pattern: distribution-archives-*
        merge-multiple: true
    - name: List distribution archives
      run: ls --recursive distribution-archives
    - name: Upload combined distribution archives
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
      with:
        name: combined-distribution-archives
        path: distribution-archives
